![Ironhack logo](https://i.imgur.com/1QgrNNw.png)

# Lab | Numpy

## Introduction

An important ability of a data scientist/data engineer is to know where and how to find information that helps you to accomplish your work. In the exercise, you will both practice the Numpy features we discussed in the lesson and learn new features by looking up documentations and references.

## Getting Started
There are a bunch of comments which instruct what you are supposed to do step by step. Follow the order of the instructions from top to bottom. Read each instruction carefully and provide your answer beneath it. You should also test your answers to make sure your responses are correct. If one of your responses is incorrect, you may not be able to proceed because later responses may depend upon previous responses.


## Resources

Some of the questions in the assignment are not covered in our lesson. You will learn how to efficiently look up the information on your own. Below are some resources you can find the information you need.

[Numpy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

[Numpy Reference](https://docs.scipy.org/doc/numpy/reference/)

[Google Search](https://www.google.com/search?q=how+to+use+numpy)



# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.__version__

'1.19.4'

#### 3. Generate a 3x2x5 3-dimensional array with random values. Assign the array to variable *a*.

**Example of output**:
````python
[[[0.29932768, 0.85812686, 0.75266145, 0.09278988, 0.78358352],
  [0.13437453, 0.65695946, 0.82047594, 0.09764179, 0.52230096]],
 
 [[0.54248247, 0.06431281, 0.65902257, 0.92736679, 0.3302839 ],
  [0.86867236, 0.33960592, 0.62295821, 0.74563567, 0.24351584]],
 
 [[0.21276812, 0.06917533, 0.35106591, 0.82273425, 0.7910178 ],
  [0.37768961, 0.56107736, 0.99965953, 0.97615549, 0.2445537 ]]]
````

In [3]:
a = np.random.random((3,2,5))

#### 4. Print *a*.


In [4]:
print(a)

[[[0.01913701 0.94067702 0.5403711  0.87252042 0.57103202]
  [0.88751363 0.39431417 0.77207192 0.58160217 0.81227803]]

 [[0.0026881  0.13492642 0.95944573 0.56109209 0.84261303]
  [0.14696918 0.47607    0.47063801 0.18868872 0.12179845]]

 [[0.17996514 0.05309338 0.51373228 0.76184646 0.09670773]
  [0.23414619 0.12540795 0.59082987 0.73591141 0.41276713]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

Expected output:

````python
      [[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]]
````

In [5]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [7]:
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [8]:
#they don't have the same shape
a + b

ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 3x2x5 array). Assign the reshaped array to variable *c*.
*Hint: The tranpose of 5x2x3 is 3x2x5*

Expected output:

````python
      [[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]]
````

In [9]:
c = b.T

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [10]:
#It works because they have the same shape

In [11]:
#Method 1
d = a + c
print(d)

[[[1.01913701 1.94067702 1.5403711  1.87252042 1.57103202]
  [1.88751363 1.39431417 1.77207192 1.58160217 1.81227803]]

 [[1.0026881  1.13492642 1.95944573 1.56109209 1.84261303]
  [1.14696918 1.47607    1.47063801 1.18868872 1.12179845]]

 [[1.17996514 1.05309338 1.51373228 1.76184646 1.09670773]
  [1.23414619 1.12540795 1.59082987 1.73591141 1.41276713]]]


In [12]:
#Method 2
d = np.add(a, c)
print(d)

[[[1.01913701 1.94067702 1.5403711  1.87252042 1.57103202]
  [1.88751363 1.39431417 1.77207192 1.58160217 1.81227803]]

 [[1.0026881  1.13492642 1.95944573 1.56109209 1.84261303]
  [1.14696918 1.47607    1.47063801 1.18868872 1.12179845]]

 [[1.17996514 1.05309338 1.51373228 1.76184646 1.09670773]
  [1.23414619 1.12540795 1.59082987 1.73591141 1.41276713]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)

[[[0.01913701 0.94067702 0.5403711  0.87252042 0.57103202]
  [0.88751363 0.39431417 0.77207192 0.58160217 0.81227803]]

 [[0.0026881  0.13492642 0.95944573 0.56109209 0.84261303]
  [0.14696918 0.47607    0.47063801 0.18868872 0.12179845]]

 [[0.17996514 0.05309338 0.51373228 0.76184646 0.09670773]
  [0.23414619 0.12540795 0.59082987 0.73591141 0.41276713]]]


In [14]:
print(d)

[[[1.01913701 1.94067702 1.5403711  1.87252042 1.57103202]
  [1.88751363 1.39431417 1.77207192 1.58160217 1.81227803]]

 [[1.0026881  1.13492642 1.95944573 1.56109209 1.84261303]
  [1.14696918 1.47607    1.47063801 1.18868872 1.12179845]]

 [[1.17996514 1.05309338 1.51373228 1.76184646 1.09670773]
  [1.23414619 1.12540795 1.59082987 1.73591141 1.41276713]]]


In [15]:
#the values in d are equal to the a values + 1 in the corresponding positions

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# Method 1
e = a * c

In [17]:
# Method 2
e = np.multiply(a, c)

In [18]:
print(e)

[[[0.01913701 0.94067702 0.5403711  0.87252042 0.57103202]
  [0.88751363 0.39431417 0.77207192 0.58160217 0.81227803]]

 [[0.0026881  0.13492642 0.95944573 0.56109209 0.84261303]
  [0.14696918 0.47607    0.47063801 0.18868872 0.12179845]]

 [[0.17996514 0.05309338 0.51373228 0.76184646 0.09670773]
  [0.23414619 0.12540795 0.59082987 0.73591141 0.41276713]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
# yes, array 'e' is equal to 'a' because they have equal values and shape
#since all the values in c were 1 the multiplication results are the same
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [20]:
print(a.shape)
print(e.shape)

(3, 2, 5)
(3, 2, 5)


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [21]:
d_max = d.max()
print(d_max)

1.9594457320426586


In [22]:
d_min = d.min()
print(d_min)

1.0026881037784936


In [23]:
d_mean = d.mean()
print(d_mean)

1.4666951589472652
